const SUPABASE_URL='https://alyqhaqpjtkxanfiezwu.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseXFoYXFwanRreGFuZmllend1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0ODQwNDIsImV4cCI6MjEwNTA2MDA0Mn0.FpeXb8CiJHcBKujMaG6oxqo0JbPmUIUFEL45B4RGqlk';
const STORAGE_KEY='tvc_v4',OLD_KEYS=['tvc_v1','tvc_v2','tvc_v3'],MIN_INTERVAL_MS=750;
let sb=null;try{sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY)}catch(e){console.error(e)}
let state={name:'',goal:100000,count:0,totalActiveMs:0,sessions:[],totalSessions:0,currentSession:null,lastCountAt:null,createdAt:null,nextChallengeAt:0,voiceEnabled:false,voiceRate:1,feedMode:false,feedPlaylistId:'',feedVideoIds:[],feedIndex:0};
let user=null,isFocused=true,selectedGoal=100000,spaceHeld=false,isCooling=false,isSpeaking=false,authMode='signin',authInProgress=false,syncTimer=null,pendingChallenge=null,coolTimer=null;
function loadLocal(){OLD_KEYS.forEach(k=>{try{localStorage.removeItem(k)}catch(e){}});try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=Object.assign(state,JSON.parse(raw));if(!state.voiceRate)state.voiceRate=1;const realSess=(state.sessions||[]).filter(s=>(s.counts||0)>0);state.sessions=realSess;if(!state.totalSessions||state.totalSessions<realSess.length)state.totalSessions=realSess.length}catch(e){}}
function saveLocal(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function clearOldLocal(){[STORAGE_KEY,...OLD_KEYS].forEach(k=>{try{localStorage.removeItem(k)}catch(e){}});state={name:'',goal:100000,count:0,totalActiveMs:0,sessions:[],totalSessions:0,currentSession:null,lastCountAt:null,createdAt:null,nextChallengeAt:0,voiceEnabled:false,voiceRate:1,feedMode:false,feedPlaylistId:'',feedVideoIds:[],feedIndex:0};saveLocal();updateUI();showToast('Old local data cleared')}
async function ensureProfile(){if(!user||!sb)return;try{const{data}=await sb.from('profiles').select('id').eq('id',user.id).maybeSingle();if(!data){const name=state.name||user.email?.split('@')[0]||'Anonymous';await sb.from('profiles').insert({id:user.id,display_name:name,username:(name.toLowerCase().replace(/[^a-z0-9]+/g,'_')||'user')+'_'+user.id.slice(0,4)})}}catch(e){console.warn(e)}}
async function loadFromCloud(){if(!user||!sb)return;try{const{data,error}=await sb.from('progress').select('*').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data){const cloudCount=data.count||0;const cloudMs=data.total_active_ms||0;if(cloudCount>state.count){state.count=cloudCount;state.goal=data.goal||state.goal;state.totalActiveMs=Math.max(state.totalActiveMs,cloudMs);if(data.voice_enabled!=null)state.voiceEnabled=!!data.voice_enabled;state.lastCountAt=data.last_count_at?new Date(data.last_count_at).getTime():state.lastCountAt;saveLocal();updateUI();showToast('Synced from cloud ('+cloudCount.toLocaleString()+')')}else if(state.count>cloudCount){await pushToCloud();showToast('Uploaded local count to cloud')}else{state.totalActiveMs=Math.max(state.totalActiveMs,cloudMs);saveLocal();showToast('Already in sync')}}else await pushToCloud()}catch(e){console.warn(e);showToast('Sync failed')}}
async function pushToCloud(){if(!user||!sb)return;try{await ensureProfile();const payload={user_id:user.id,goal:state.goal,count:state.count,total_active_ms:state.totalActiveMs+(state.currentSession?Date.now()-state.currentSession.start:0),voice_enabled:state.voiceEnabled,last_count_at:state.lastCountAt?new Date(state.lastCountAt).toISOString():null,updated_at:new Date().toISOString()};const{error}=await sb.from('progress').upsert(payload,{onConflict:'user_id'});if(error)throw error}catch(e){console.warn(e)}}
function scheduleSync(){if(!user)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushToCloud(),1500)}
async function loadLeaderboard(){const list=document.getElementById('leaderboardList');if(!sb){list.innerHTML='<div class="empty">Unavailable</div>';return}try{const{data,error}=await sb.from('leaderboard').select('*').limit(20);if(error)throw error;if(!data||!data.length){list.innerHTML='<div class="empty">No one on the board yet.</div>';return}list.innerHTML=data.map((row,i)=>`<div class="lb-row"><span class="lb-rank">#${i+1}</span><span class="lb-name">${esc(row.display_name||row.username||'Anonymous')}</span><span class="lb-count">${formatNumber(row.count||0)}</span></div>`).join('')}catch(e){list.innerHTML='<div class="empty">Could not load</div>'}}
function getProofQuery(){const p=new URLSearchParams(location.search);return (p.get('u')||p.get('proof')||p.get('user')||'').trim()}
function msToHMPublic(ms){const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return h+'h '+m+'m'}
async function loadPublicProof(key){if(!sb){document.getElementById('proofMeta').textContent='Unavailable';return true}try{let row=null;let r=await sb.from('leaderboard').select('*').eq('username',key).maybeSingle();if(!r.error&&r.data)row=r.data;if(!row){const r2=await sb.from('leaderboard').select('*').ilike('display_name',key).limit(1);if(r2.data&&r2.data[0])row=r2.data[0]}if(!row){const r3=await sb.from('leaderboard').select('*').ilike('username',key+'%').limit(1);if(r3.data&&r3.data[0])row=r3.data[0]}if(!row){document.getElementById('proofName').textContent='Not found';document.getElementById('proofMeta').textContent='No public profile for '+key+'. Sign in and sync first.';return true}const count=row.count||0;const goal=row.goal||100000;const pct=Math.min(100,(count/Math.max(1,goal))*100);document.getElementById('proofName').textContent=row.display_name||row.username||'Counter';document.getElementById('proofCount').textContent=formatNumber(count);document.getElementById('proofMeta').textContent='@'+(row.username||'user')+' · toward '+formatNumber(goal);document.getElementById('proofFill').style.width=pct+'%';document.getElementById('proofPct').textContent=pct.toFixed(2)+'%';document.getElementById('proofGoal').textContent=formatNumber(goal)+' goal';document.getElementById('proofTime').textContent=msToHMPublic(row.total_active_ms||0);const upd=row.updated_at?new Date(row.updated_at):null;document.getElementById('proofUpdated').textContent=upd?upd.toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—';document.title=(row.display_name||row.username)+' · TVC proof';return true}catch(e){console.warn(e);document.getElementById('proofMeta').textContent='Could not load proof.';return true}}
function showProofMode(on){const view=document.getElementById('proofView');const header=document.querySelector('header');const main=document.querySelector('main');const phil=document.querySelector('.philosophy');if(view)view.style.display=on?'block':'none';if(header)header.style.display=on?'none':'flex';if(main)main.style.display=on?'none':'grid';if(phil)phil.style.display=on?'none':'block'}
async function copyProofLink(){let uname='';if(user&&sb){try{const{data}=await sb.from('profiles').select('username,display_name').eq('id',user.id).maybeSingle();if(data&&data.username)uname=data.username}catch(e){}}if(!uname&&state.name){uname=state.name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'user'}if(!uname){showToast('Sign in and sync first');return}const base=location.origin+location.pathname.replace(/index\.html$/,'');const url=base+(base.endsWith('/')?'':'/')+'?u='+encodeURIComponent(uname);try{await navigator.clipboard.writeText(url);showToast('Proof link copied')}catch(e){prompt('Copy this proof link:',url)}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]))}
const FEED_DISCOVER={shorts:{listType:'search',list:'youtube shorts'},study:{listType:'search',list:'study with me'},lofi:{listType:'search',list:'lofi hip hop radio'},news:{listType:'search',list:'world news today'},tech:{listType:'search',list:'technology explained'}};
let ytPlayer=null,ytReady=false;
function onYouTubeIframeAPIReady(){ytReady=true;if(state.feedMode)setupFeedPlayer()}
window.onYouTubeIframeAPIReady=onYouTubeIframeAPIReady;
function parseYouTubeInput(raw){const s=(raw||'').trim();if(!s)return null;let list=null,vid=null;try{const u=new URL(s.startsWith('http')?s:'https://'+s);list=u.searchParams.get('list');if(u.hostname.includes('youtu.be'))vid=u.pathname.slice(1).split('/')[0];else if(u.pathname.includes('/shorts/'))vid=u.pathname.split('/shorts/')[1].split('/')[0];else if(u.pathname.includes('/embed/'))vid=u.pathname.split('/embed/')[1].split('/')[0];else if(u.pathname.includes('/watch'))vid=u.searchParams.get('v');else if(u.pathname.includes('/playlist'))list=list||u.searchParams.get('list')}catch(e){if(/^[\w-]{11}$/.test(s))vid=s;if(/^PL[\w-]+$/.test(s)||/^UU[\w-]+$/.test(s))list=s}return{list,vid}}
function setupFeedPlayer(discoverKey){
  const wrap=document.getElementById('feedFrameWrap');
  if(!wrap)return;
  let listType=null,list=null,vid=null;
  if(discoverKey&&FEED_DISCOVER[discoverKey]){
    listType=FEED_DISCOVER[discoverKey].listType;
    list=FEED_DISCOVER[discoverKey].list;
    state.feedPlaylistId='discover:'+discoverKey;
    document.querySelectorAll('.feed-chip').forEach(c=>c.classList.toggle('active',c.dataset.discover===discoverKey));
  }else{
    const parsed=parseYouTubeInput(document.getElementById('feedUrlInput')?.value||state.feedPlaylistId);
    if(!parsed||(!parsed.list&&!parsed.vid)){showToast('Paste a YouTube link or pick a topic');return}
    if(parsed.list){listType='playlist';list=parsed.list;state.feedPlaylistId=parsed.list}
    if(parsed.vid){vid=parsed.vid;state.feedVideoIds=[parsed.vid];state.feedIndex=0}
    document.querySelectorAll('.feed-chip').forEach(c=>c.classList.remove('active'));
  }
  saveLocal();
  wrap.style.display='block';
  const elId='feedFrame';
  const host=document.getElementById(elId);
  if(host){
    const div=document.createElement('div');
    div.id=elId;
    host.parentNode.replaceChild(div,host);
  }
  const start=()=>{
    if(typeof YT==='undefined'||!YT.Player){setTimeout(start,200);return}
    if(ytPlayer&&ytPlayer.destroy)try{ytPlayer.destroy()}catch(e){}
    const opts={height:'100%',width:'100%',playerVars:{autoplay:1,rel:0,modestbranding:1,playsinline:1}};
    if(listType==='search'&&list){opts.playerVars.listType='search';opts.playerVars.list=list}
    else if(listType==='playlist'&&list){opts.playerVars.listType='playlist';opts.playerVars.list=list}
    else if(vid){opts.videoId=vid}
    else{showToast('Nothing to play');return}
    ytPlayer=new YT.Player(elId,{...opts,events:{
      onReady:()=>showToast(discoverKey?'Playing '+discoverKey:'Feed ready'),
      onError:(e)=>{console.warn('YT error',e);showToast('Video unavailable — try Next or another topic')}
    }});
  };
  start();
}
function feedNextVideo(){if(!ytPlayer){showToast('Load a feed first');return false}try{if(typeof ytPlayer.nextVideo==='function'){ytPlayer.nextVideo();return true}if(state.feedVideoIds&&state.feedVideoIds.length){state.feedIndex=(state.feedIndex+1)%state.feedVideoIds.length;ytPlayer.loadVideoById(state.feedVideoIds[state.feedIndex]);return true}}catch(e){console.warn(e)}showToast('Could not skip — try another topic');return false}
function syncFeedUI(){const on=!!state.feedMode;const t=document.getElementById('feedToggle');if(t)t.classList.toggle('on',on);const lab=document.getElementById('feedToggleLabel');if(lab)lab.textContent=on?'Feed mode on':'Feed mode off';const panel=document.getElementById('feedPanel');if(panel){panel.classList.toggle('on',on);panel.style.display=on?'block':'none'}const row=document.getElementById('feedNextRow');if(row)row.style.display=on?'flex':'none';if(document.getElementById('feedUrlInput')&&state.feedPlaylistId&&!String(state.feedPlaylistId).startsWith('discover')&&!document.getElementById('feedUrlInput').value){document.getElementById('feedUrlInput').value=state.feedPlaylistId.startsWith('http')?state.feedPlaylistId:'https://www.youtube.com/playlist?list='+state.feedPlaylistId}}
function toggleFeedMode(){state.feedMode=!state.feedMode;if(state.currentSession)state.currentSession.mode=state.feedMode?'feed':'focus';syncFeedUI();saveLocal();showToast(state.feedMode?'Feed mode on':'Feed mode off');if(state.feedMode){if(state.feedPlaylistId&&!String(state.feedPlaylistId).startsWith('discover:')&&!String(state.feedPlaylistId).startsWith('discover'))setupFeedPlayer();else setupFeedPlayer('shorts')}}
async function doNextFeed(){if(!state.feedMode){showToast('Turn on Feed mode first');return}if(!canCount()){if(!isFocused)showToast('Stay focused on this tab');return}if(!state.currentSession)startSession();state.currentSession.mode='feed';state.count+=1;celebrateMilestone(state.count);const now=Date.now();state.currentSession.counts+=1;state.currentSession.timestamps.push(now);state.lastCountAt=now;if(state.currentSession.timestamps.length>400)state.currentSession.timestamps=state.currentSession.timestamps.slice(-300);const display=document.getElementById('countDisplay');display.classList.add('pulse');setTimeout(()=>display.classList.remove('pulse'),120);setButtonCooling(true,state.voiceEnabled?'speaking...':'wait...');const nb=document.getElementById('nextFeedBtn');if(nb)nb.disabled=true;feedNextVideo();await speakNumber(state.count);if(state.count>=state.goal)document.getElementById('finishedBanner').style.display='block';if(!pendingChallenge&&state.nextChallengeAt&&state.count>=state.nextChallengeAt)showChallenge();else if(!state.nextChallengeAt&&state.count>=20)scheduleNextChallenge();saveLocal();scheduleSync();updateUI();setTimeout(()=>{setButtonCooling(false,'or press Space');if(nb)nb.disabled=false},MIN_INTERVAL_MS)}
function updateNotesJournal(){const el=document.getElementById('notesJournal');if(!el)return;const notes=[];if(state.currentSession&&state.currentSession.note)notes.push({...state.currentSession,live:true});[...(state.sessions||[])].reverse().forEach(s=>{if(s.note&&s.note.trim())notes.push(s)});if(!notes.length){el.innerHTML='<div class="empty">Notes you save while counting show up here</div>';return}el.innerHTML=notes.slice(0,40).map(s=>{const mode=(s.mode||'focus');const when=new Date(s.start).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});const live=s.live?' · live':'';return '<div class="note-entry"><div class="note-meta"><span class="note-mode '+mode+'">'+mode+'</span>+'+(s.counts||0)+' counts · '+when+live+'</div><div class="note-body">'+esc(s.note)+'</div></div>'}).join('')}
function formatNumber(n){return n.toLocaleString('en-US')}
async function checkSession(){if(!sb)return;try{const{data:{session}}=await sb.auth.getSession();user=session?.user||null;updateAuthUI();if(user){document.getElementById('signOutBtn').style.display='block';await loadFromCloud()}}catch(e){console.warn(e)}loadLeaderboard()}
function updateAuthUI(){const status=document.getElementById('authStatus'),btn=document.getElementById('authBtn');if(user){const alias=state.name||user.email?.split('@')[0]||'Account';status.textContent=alias;status.classList.add('logged');btn.textContent='Account'}else{status.textContent='Not signed in';status.classList.remove('logged');btn.textContent='Sign in'}}
async function handleAuth(){if(authInProgress||!sb)return;const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,errEl=document.getElementById('authError');errEl.classList.remove('show');if(!email||!password){errEl.textContent='Email and password required';errEl.classList.add('show');return}if(password.length<6){errEl.textContent='Min 6 characters';errEl.classList.add('show');return}authInProgress=true;const btn=document.getElementById('authSubmitBtn');btn.disabled=true;try{let result=authMode==='signin'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password});if(result.error)throw result.error;user=result.data.user;updateAuthUI();if(user){document.getElementById('signOutBtn').style.display='block';await loadFromCloud();showToast(authMode==='signin'?'Signed in':'Account created');document.getElementById('authModal').style.display='none'}}catch(e){errEl.textContent=e.message||'Auth failed';errEl.classList.add('show')}finally{authInProgress=false;btn.disabled=false;btn.textContent=authMode==='signin'?'Sign in':'Sign up'}}
async function signOut(){if(sb)await sb.auth.signOut();user=null;updateAuthUI();document.getElementById('signOutBtn').style.display='none';showToast('Signed out')}
function scheduleNextChallenge(){state.nextChallengeAt=state.count+35+Math.floor(Math.random()*56)}
function makeChallenge(){const a=2+Math.floor(Math.random()*12),b=2+Math.floor(Math.random()*12);return[{text:a+' + '+b,answer:a+b},{text:(a+b)+' - '+a,answer:b},{text:a+' × '+b,answer:a*b}][Math.floor(Math.random()*3)]}
function showChallenge(){if(pendingChallenge)return;pendingChallenge=makeChallenge();document.getElementById('challengeText').textContent='What is '+pendingChallenge.text+'?';document.getElementById('challengeInput').value='';document.getElementById('challengeBox').style.display='block';document.getElementById('countBtn').disabled=true}
function submitChallenge(){if(!pendingChallenge)return;const num=parseInt(document.getElementById('challengeInput').value.trim(),10);if(num===pendingChallenge.answer){pendingChallenge=null;document.getElementById('challengeBox').style.display='none';document.getElementById('countBtn').disabled=false;scheduleNextChallenge();saveLocal();showToast('Presence confirmed')}else{showToast('Wrong answer');document.getElementById('challengeInput').value=''}}
function syncVoiceUI(){const on=!!state.voiceEnabled;const card=document.getElementById('voiceToggleCard');const settings=document.getElementById('voiceToggle');if(card){card.classList.toggle('on',on);const lab=document.getElementById('voiceToggleLabel');if(lab)lab.textContent=on?'Voice on':'Voice off'}if(settings)settings.classList.toggle('on',on);const row=document.getElementById('voiceRateRow');if(row)row.style.display=on?'flex':'none';document.querySelectorAll('.voice-rate-chip').forEach(ch=>{ch.classList.toggle('active',String(state.voiceRate||1)===ch.dataset.rate)})}
function toggleVoice(){state.voiceEnabled=!state.voiceEnabled;if(!state.voiceEnabled&&window.speechSynthesis)try{speechSynthesis.cancel()}catch(e){}isSpeaking=false;syncVoiceUI();showToast(state.voiceEnabled?'Voice on':'Voice off');saveLocal();scheduleSync()}
async function submitTipWaitlist(){const wantReceive=document.getElementById('tipWantReceive').checked;const wantGive=document.getElementById('tipWantGive').checked;const email=(document.getElementById('tipEmail').value||'').trim();const msg=document.getElementById('tipWaitlistMsg');if(!wantReceive&&!wantGive){showToast('Pick at least one option');return}const btn=document.getElementById('tipWaitlistBtn');btn.disabled=true;try{if(sb){const{error}=await sb.from('tip_interest').insert({user_id:user?user.id:null,display_name:state.name||null,email:email||null,want_receive:wantReceive,want_give:wantGive});if(error)throw error}msg.style.display='block';msg.textContent='You are on the list.';showToast('Joined waitlist')}catch(e){try{const list=JSON.parse(localStorage.getItem('tvc_tip_interest')||'[]');list.push({wantReceive,wantGive,email,at:Date.now()});localStorage.setItem('tvc_tip_interest',JSON.stringify(list));msg.style.display='block';msg.textContent='Saved locally.';showToast('Saved locally')}catch(e2){showToast('Could not save')}}finally{btn.disabled=false;btn.textContent='Join waitlist'}}
const MILESTONES=new Set([67,69,111,222,333,444,555,666,777,888,999,1111,1221,2222,3333,4444,5555,6666,6969,7777,8888,9999,10000,11111,22222,25000,33333,42000,50000,55555,66666,77777,88888,99999,100000]);
function isAestheticNumber(n){if(MILESTONES.has(n))return true;const s=String(n);if(s.length>=3&&new Set(s).size===1)return true;if(s.length>=4&&s===s.split('').reverse().join(''))return true;return false}
function fireConfetti(){const layer=document.getElementById('confettiLayer');if(!layer)return;const colors=['#38bdf8','#34d399','#fbbf24','#f87171','#a78bfa'];for(let i=0;i<40;i++){const el=document.createElement('div');el.className='confetti-piece';el.style.left=(Math.random()*100)+'%';el.style.background=colors[i%colors.length];el.style.animationDelay=(Math.random()*0.4)+'s';layer.appendChild(el);setTimeout(()=>el.remove(),2400)}}
function celebrateMilestone(n){if(!isAestheticNumber(n))return;fireConfetti();const t=document.getElementById('milestoneToast');if(t){t.textContent='Milestone '+n.toLocaleString();t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}showToast('Milestone: '+n.toLocaleString())}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function wrapText(ctx,text,x,y,maxW,lineH){const words=text.split(' ');let line='',yy=y;for(const w of words){const test=line+w+' ';if(ctx.measureText(test).width>maxW&&line){ctx.fillText(line.trim(),x,yy);line=w+' ';yy+=lineH}else line=test}if(line)ctx.fillText(line.trim(),x,yy)}
function buildShareCardCanvas(){const W=1080,H=1350;const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#0b1220');g.addColorStop(1,'#0f172a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#38bdf8';ctx.fillRect(0,0,W,12);ctx.fillStyle='#9ca3af';ctx.font='600 28px Inter,system-ui,sans-serif';ctx.fillText('TIME VALUE COUNTER',72,90);ctx.fillStyle='#f3f4f6';ctx.font='800 56px Inter,system-ui,sans-serif';ctx.fillText((state.name||'Counter').slice(0,28),72,160);ctx.fillStyle='#38bdf8';ctx.font='700 140px monospace';ctx.fillText(state.count.toLocaleString('en-US'),72,360);ctx.fillStyle='#9ca3af';ctx.font='500 36px Inter,system-ui,sans-serif';ctx.fillText('of '+state.goal.toLocaleString('en-US')+' focused counts',72,420);const pct=Math.min(1,state.count/Math.max(1,state.goal));ctx.fillStyle='#1f2937';roundRect(ctx,72,460,W-144,24,12);ctx.fill();ctx.fillStyle='#38bdf8';roundRect(ctx,72,460,Math.max(12,(W-144)*pct),24,12);ctx.fill();ctx.fillStyle='#9ca3af';ctx.font='600 28px Inter,system-ui,sans-serif';ctx.fillText((pct*100).toFixed(2)+'% complete',72,530);const activeMs=state.totalActiveMs+(state.currentSession?Date.now()-state.currentSession.start:0);const rate=activeMs>0?(state.count/(activeMs/3600000)):0;let eta='—';if(rate>0&&state.count<state.goal)eta=new Date(Date.now()+((state.goal-state.count)/rate)*3600000).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});const sessions=(state.totalSessions||0)+((state.currentSession&&state.currentSession.counts>0)?1:0);const stats=[{l:'ACTIVE TIME',v:msToHM(activeMs)},{l:'SESSIONS',v:String(sessions)},{l:'PER HOUR',v:rate>0?String(Math.round(rate)):'—'},{l:'EST. FINISH',v:eta}];const boxW=(W-72*2-24*3)/4;stats.forEach((s,i)=>{const x=72+i*(boxW+24);ctx.fillStyle='#1f2937';roundRect(ctx,x,580,boxW,140,20);ctx.fill();ctx.fillStyle='#38bdf8';ctx.font='700 32px monospace';ctx.fillText(s.v.slice(0,12),x+16,650);ctx.fillStyle='#9ca3af';ctx.font='600 18px Inter,system-ui,sans-serif';ctx.fillText(s.l,x+16,700)});ctx.fillStyle='#9ca3af';ctx.font='500 30px Inter,system-ui,sans-serif';wrapText(ctx,'Every number is focused attention. Most people will never count this high.',72,800,W-144,42);ctx.fillStyle='#38bdf8';ctx.font='700 32px Inter,system-ui,sans-serif';ctx.fillText('What is your time actually worth?',72,920);ctx.fillStyle='#374151';ctx.fillRect(72,1100,W-144,2);ctx.fillStyle='#9ca3af';ctx.font='500 24px Inter,system-ui,sans-serif';ctx.fillText('Proven presence · Human pace',72,1160);ctx.fillText(new Date().toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}),72,1205);return canvas}
function canvasToBlob(canvas){return new Promise(r=>canvas.toBlob(r,'image/png'))}
async function shareCardImage(){try{showToast('Creating share card...');const canvas=buildShareCardCanvas();const blob=await canvasToBlob(canvas);if(!blob){showToast('Could not create image');return}const file=new File([blob],'tvc-progress-'+state.count+'.png',{type:'image/png'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:'Time Value Counter',text:'I am at '+state.count.toLocaleString()+' focused counts on TVC.'});showToast('Shared');return}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tvc-progress-'+state.count+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);showToast('PNG saved - post it anywhere')}catch(e){console.warn(e);try{const canvas=buildShareCardCanvas();const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='tvc-progress-'+state.count+'.png';a.click();showToast('PNG downloaded')}catch(e2){showToast('Share failed')}}}
function canCount(){if(!isFocused||isCooling||isSpeaking)return false;if(pendingChallenge)return false;if(state.lastCountAt&&Date.now()-state.lastCountAt<MIN_INTERVAL_MS)return false;return true}
function setButtonCooling(on,label){isCooling=on;const btn=document.getElementById('countBtn');if(!on)isSpeaking=false;btn.classList.toggle('cooling',on);btn.disabled=on||!!pendingChallenge;if(label)document.getElementById('countHint').textContent=label;if(coolTimer)clearTimeout(coolTimer);if(on){coolTimer=setTimeout(()=>{isCooling=false;isSpeaking=false;btn.classList.remove('cooling');if(!pendingChallenge)btn.disabled=false;document.getElementById('countHint').textContent='or press Space'},8000)}}
async function speakNumber(n){if(!state.voiceEnabled)return;isSpeaking=true;try{if(window.speechSynthesis)speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(String(n));const rate=Math.min(2,Math.max(0.7,Number(state.voiceRate)||1));utter.rate=rate*0.95;await new Promise((resolve)=>{let done=false;const finish=()=>{if(done)return;done=true;resolve()};utter.onend=finish;utter.onerror=finish;setTimeout(finish,Math.max(2500,4000/rate));speechSynthesis.speak(utter)})}catch(e){}finally{isSpeaking=false}}
async function doCount(){if(!canCount()){if(!isFocused)showToast('Stay focused on this tab');return}if(!state.currentSession)startSession();if(state.currentSession&&!state.currentSession.mode)state.currentSession.mode=state.feedMode?'feed':'focus';state.count+=1;celebrateMilestone(state.count);const now=Date.now();state.currentSession.counts+=1;state.currentSession.timestamps.push(now);state.lastCountAt=now;if(state.currentSession.timestamps.length>400)state.currentSession.timestamps=state.currentSession.timestamps.slice(-300);const display=document.getElementById('countDisplay');display.classList.add('pulse');setTimeout(()=>display.classList.remove('pulse'),120);setButtonCooling(true,state.voiceEnabled?'speaking...':'wait...');await speakNumber(state.count);if(state.count>=state.goal)document.getElementById('finishedBanner').style.display='block';if(!pendingChallenge&&state.nextChallengeAt&&state.count>=state.nextChallengeAt)showChallenge();else if(!state.nextChallengeAt&&state.count>=20)scheduleNextChallenge();saveLocal();scheduleSync();updateUI();setTimeout(()=>setButtonCooling(false,'or press Space'),MIN_INTERVAL_MS)}
function startSession(){state.currentSession={start:Date.now(),counts:0,timestamps:[],note:'',mode:state.feedMode?'feed':'focus'}}
function endSession(){if(!state.currentSession)return;const s=state.currentSession;s.end=Date.now();if((s.counts||0)>0){state.sessions.push(s);state.totalSessions=(state.totalSessions||0)+1;if(state.sessions.length>30)state.sessions=state.sessions.slice(-30)}state.currentSession=null;saveLocal()}
function sessionPaceTag(s){if(!s||!s.counts)return 'ok';const dur=Math.max(1,(s.end||Date.now())-s.start);const perMin=s.counts/(dur/60000);if(perMin>=8)return 'good';if(perMin>=4)return 'ok';return 'slow'}
function updateFormRow(){const row=document.getElementById('formRow');if(!row)return;const items=[];[...state.sessions].slice(-7).forEach(s=>{const tag=sessionPaceTag(s);const letter=tag==='good'?'F':(tag==='ok'?'S':'L');items.push('<div class="form-pill '+tag+'">'+letter+'</div>')});if(state.currentSession&&state.currentSession.counts>0)items.push('<div class="form-pill live">•</div>');row.innerHTML=items.length?items.join(''):'<span style="font-size:.8rem;color:var(--muted)">Sessions appear here</span>'}
function updateComparisons(){const grid=document.getElementById('compareGrid');if(!grid)return;const activeMs=state.totalActiveMs+(state.currentSession?Date.now()-state.currentSession.start:0);if(state.count<5||activeMs<10000){grid.innerHTML='<div class="compare-item">Start counting to see comparisons</div>';return}const hours=activeMs/3600000,mins=activeMs/60000;const shorts=Math.floor(activeMs/15000);const items=[];items.push('In this focused time you could have scrolled about <strong>'+shorts.toLocaleString()+'</strong> short videos (~15s each).');items.push('In this time, a minimum-wage worker would have earned about <strong>$'+(hours*7.25).toFixed(2)+'</strong>.');items.push('Your heart beat roughly <strong>'+Math.round(mins*70).toLocaleString()+'</strong> times.');items.push('You have placed <strong>'+formatNumber(state.count)+'</strong> deliberate counts.');const now=new Date();const end=new Date(now.getFullYear()+1,0,1);const secLeft=Math.max(0,Math.floor((end-now)/1000));const daysLeft=Math.max(1,Math.ceil(secLeft/86400));const left=Math.max(0,state.goal-state.count);const perDay=Math.ceil(left/daysLeft);if(state.count<state.goal)items.push('Year ends in <strong>'+daysLeft+'</strong> days — about <strong>'+perDay.toLocaleString()+'</strong> counts/day to finish your goal.');grid.innerHTML=items.slice(0,6).map(t=>'<div class="compare-item">'+t+'</div>').join('')}
function updateUI(){document.getElementById('countDisplay').textContent=formatNumber(state.count);const pct=(state.count/state.goal)*100;document.getElementById('progressFill').style.width=Math.min(pct,100)+'%';document.getElementById('percentText').textContent=pct.toFixed(3)+'%';document.getElementById('remainingText').textContent=formatNumber(Math.max(state.goal-state.count,0))+' left';document.getElementById('goalLabel').textContent='Counting toward '+formatNumber(state.goal);const activeMs=state.totalActiveMs+(state.currentSession?Date.now()-state.currentSession.start:0);document.getElementById('totalTime').textContent=msToHM(activeMs);document.getElementById('sessionsCount').textContent=(state.totalSessions||0)+((state.currentSession&&state.currentSession.counts>0)?1:0);const rate=activeMs>0?(state.count/(activeMs/3600000)):0;document.getElementById('avgRate').textContent=rate>0?rate.toFixed(0):'—';const perMin=state.currentSession&&(Date.now()-state.currentSession.start)>0?(state.currentSession.counts/((Date.now()-state.currentSession.start)/60000)).toFixed(1):'—';document.getElementById('rateText').textContent=perMin+' / min';document.getElementById('sessionTime').textContent='Session: '+(state.currentSession?Math.floor((Date.now()-state.currentSession.start)/60000):0)+'m';let etaText='—';if(rate>0&&state.count<state.goal){const hoursLeft=(state.goal-state.count)/rate;etaText=new Date(Date.now()+hoursLeft*3600000).toLocaleDateString('en-US',{month:'short',day:'numeric'})}document.getElementById('eta').textContent=etaText;const hist=document.getElementById('historyList');if(!state.sessions.length&&!state.currentSession)hist.innerHTML='<div class="empty">Start counting to build your log</div>';else{const recent=[...state.sessions].reverse().slice(0,8);hist.innerHTML=recent.map(s=>'<div class="history-item"><span class="history-count">+'+s.counts+'</span><span class="history-meta"> · '+(s.mode||'focus')+' · '+new Date(s.start).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})+(s.note?' · '+esc(s.note):'')+'</span></div>').join('')}const noteEl=document.getElementById('noteInput');if(document.activeElement!==noteEl)noteEl.value=state.currentSession?.note||'';const sn=document.getElementById('seasonName');if(sn)sn.textContent=state.name||'Counter';updateFormRow();updateComparisons();syncVoiceUI();syncFeedUI();updateNotesJournal();updateAuthUI()}
function msToHM(ms){const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000);return h+'h '+m+'m'}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2500)}
function handleVisibility(){isFocused=!document.hidden;if(document.hidden&&window.speechSynthesis){try{speechSynthesis.cancel()}catch(e){}}isSpeaking=false;document.getElementById('focusBanner').classList.toggle('visible',!isFocused);document.getElementById('focusDot').classList.toggle('danger',!isFocused);document.getElementById('focusText').textContent=isFocused?'Focused':'Away';if(!isFocused&&state.currentSession){if((state.currentSession.counts||0)>0){state.totalActiveMs+=Date.now()-state.currentSession.start}endSession();scheduleSync()}}
function init(){const proofKey=getProofQuery();if(proofKey){showProofMode(true);loadPublicProof(proofKey);const pcb=document.getElementById('proofCopyBtn');if(pcb)pcb.addEventListener('click',()=>{const url=location.href.split('#')[0];navigator.clipboard.writeText(url).then(()=>showToast('Link copied')).catch(()=>prompt('Copy:',url))});const pob=document.getElementById('proofOpenAppBtn');if(pob)pob.addEventListener('click',()=>{location.href=location.pathname});return}showProofMode(false);loadLocal();syncVoiceUI();updateUI();if(!state.name&&state.count===0)document.getElementById('onboarding').style.display='flex';if(state.currentSession&&!(state.currentSession.counts>0))state.currentSession=null;checkSession();
document.querySelectorAll('#goalChips .goal-chip,#settingsGoalChips .goal-chip').forEach(btn=>{btn.addEventListener('click',()=>{btn.parentElement.querySelectorAll('.goal-chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');selectedGoal=parseInt(btn.dataset.goal,10)})});
document.getElementById('countBtn').addEventListener('click',doCount);
document.getElementById('challengeSubmit').addEventListener('click',submitChallenge);
document.getElementById('challengeInput').addEventListener('keydown',e=>{if(e.key==='Enter')submitChallenge()});
document.getElementById('saveNoteBtn').addEventListener('click',()=>{if(!state.currentSession)startSession();state.currentSession.note=document.getElementById('noteInput').value.trim();if(!state.currentSession.mode)state.currentSession.mode=state.feedMode?'feed':'focus';saveLocal();updateNotesJournal();showToast('Note saved')});
document.getElementById('exportBtn').addEventListener('click',exportLog);
document.getElementById('exportCardBtn').addEventListener('click',exportLog);
document.getElementById('shareCountBtn').addEventListener('click',shareCardImage);
document.getElementById('copyProofBtn').addEventListener('click',copyProofLink);
document.getElementById('exportSettingsBtn').addEventListener('click',()=>{exportLog();document.getElementById('settingsModal').style.display='none'});
document.getElementById('settingsBtn').addEventListener('click',openSettings);
document.getElementById('closeSettingsBtn').addEventListener('click',()=>document.getElementById('settingsModal').style.display='none');
document.getElementById('saveSettingsBtn').addEventListener('click',saveSettings);
document.getElementById('signOutBtn').addEventListener('click',signOut);
document.getElementById('clearLocalBtn').addEventListener('click',clearOldLocal);
document.getElementById('authBtn').addEventListener('click',()=>{if(user){openSettings();return}document.getElementById('authModal').style.display='flex'});
document.getElementById('authCloseBtn').addEventListener('click',()=>document.getElementById('authModal').style.display='none');
document.getElementById('authSubmitBtn').addEventListener('click',handleAuth);
document.getElementById('authToggleMode').addEventListener('click',()=>{authMode=authMode==='signin'?'signup':'signin';document.getElementById('authTitle').textContent=authMode==='signin'?'Sign in':'Create account';document.getElementById('authSubmitBtn').textContent=authMode==='signin'?'Sign in':'Sign up';document.getElementById('authToggleMode').textContent=authMode==='signin'?'Need an account? Sign up':'Already have an account? Sign in'});
document.getElementById('startBtn').addEventListener('click',startOnboarding);
document.getElementById('voiceToggle').addEventListener('click',toggleVoice);
document.getElementById('voiceToggleCard').addEventListener('click',toggleVoice);
document.getElementById('feedToggle').addEventListener('click',toggleFeedMode);
document.getElementById('feedLoadBtn').addEventListener('click',()=>{setupFeedPlayer();saveLocal()});
document.querySelectorAll('.feed-chip').forEach(ch=>{ch.addEventListener('click',()=>{setupFeedPlayer(ch.dataset.discover);saveLocal()})});
document.getElementById('nextFeedBtn').addEventListener('click',doNextFeed);
document.getElementById('tipWaitlistBtn').addEventListener('click',submitTipWaitlist);
document.getElementById('syncNowBtn').addEventListener('click',async()=>{if(!user){showToast('Sign in to sync');return}showToast('Syncing...');await loadFromCloud();await pushToCloud()});
document.querySelectorAll('.voice-rate-chip').forEach(ch=>{ch.addEventListener('click',()=>{state.voiceRate=parseFloat(ch.dataset.rate)||1;saveLocal();syncVoiceUI();showToast('Voice speed '+state.voiceRate+'x')})});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target.tagName!=='TEXTAREA'&&e.target.tagName!=='INPUT'){e.preventDefault();if(spaceHeld)return;spaceHeld=true;doCount()}});
document.addEventListener('keyup',e=>{if(e.code==='Space')spaceHeld=false});
document.addEventListener('visibilitychange',handleVisibility);
setInterval(()=>{if(state.currentSession&&isFocused)updateUI()},1000);
setInterval(loadLeaderboard,90000);
window.addEventListener('beforeunload',()=>{if(state.currentSession){if((state.currentSession.counts||0)>0)state.totalActiveMs+=Date.now()-state.currentSession.start;endSession();if(user)pushToCloud()}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function startOnboarding(){const name=document.getElementById('nameInput').value.trim()||'Anonymous';state.name=name;state.goal=selectedGoal;state.createdAt=Date.now();state.count=0;state.totalActiveMs=0;state.sessions=[];state.totalSessions=0;state.lastCountAt=null;state.currentSession=null;scheduleNextChallenge();saveLocal();document.getElementById('onboarding').style.display='none';updateUI();showToast('Welcome, '+name)}
function openSettings(){document.getElementById('settingsName').value=state.name;selectedGoal=state.goal;document.querySelectorAll('#settingsGoalChips .goal-chip').forEach(b=>{b.classList.toggle('active',parseInt(b.dataset.goal,10)===state.goal)});syncVoiceUI();document.getElementById('settingsModal').style.display='flex'}
function saveSettings(){const name=document.getElementById('settingsName').value.trim();if(name)state.name=name;state.goal=selectedGoal;saveLocal();scheduleSync();if(user&&sb&&name){(async()=>{try{const uname=(name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')||'user')+'_'+user.id.slice(0,4);await sb.from('profiles').upsert({id:user.id,display_name:name,username:uname})}catch(e){console.warn(e)}})()}document.getElementById('settingsModal').style.display='none';updateUI();showToast('Settings saved')}
function exportLog(){const log={name:state.name,goal:state.goal,count:state.count,totalActiveMs:state.totalActiveMs,totalSessions:state.totalSessions,sessions:state.sessions,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(log,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tvc-log-'+Date.now()+'.json';a.click();showToast('Log exported')}
init();
